project: 
  type: website

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto

metadata-files:
  - _website.yml
  - _topnav_sefsc.yml
  - _metadata.yml
